### PR TITLE
Python 3 iterators

### PR DESCRIPTION
**Pull request by sdcooke**
This is the other 3 PRs (zip, xrange, and iterators) with merge conflicts resolved. Is it ok for you to merge this or would you prefer I split them out again?

### CODE REVIEW

**Comment by csilvers** [comment]
I merged this in -- I think it wasn't worth the effort to separate the three changes out -- but I notice now that travis is failing.  Can you look into those test failures and see if it's anything that needs to be fixed up?

**Comment by csilvers** [comment]
Also, if this is the last thing needed for python3, let's see if we can add python3 support to travis, so we don't backslide on the python3 support!  @kevinbarabash any tips on how to do that?

**Comment by csilvers** [comment]
(Never mind, I see you said in #8.)

@sdcooke are you interested in adding `python=3.5` (or whatever) to the travis config file?

**Comment by sdcooke** [comment]
I have never used travis before so I'm not sure exactly how to add it...locally I was testing with 3.6.1

**Comment by kevinbarabash** [comment]
@sdcooke modify .travis.yml to look like:
```
language: python
python:
  - "2.7"
  - "3.6"
install:
  - python setup.py install
script:
  - python -m unittest discover -s tinyquery -p "*_test.py"
```
I don't think travis-ci supports specifying patch versions.

**Pull request merged**
